#!/bin/bash
# --------------------------------------------------------------------
# GEOS-Chem Environment Setup Script
# --------------------------------------------------------------------

set -euo pipefail

BASE_DIR="/opt/geos-chem"
NETCDF_DIR="${BASE_DIR}/netcdf"
ENV_FILE="${BASE_DIR}/env/wrfgc.env"

echo "Creating GEOS-Chem directory structure..."
mkdir -p "${NETCDF_DIR}/bin" "${NETCDF_DIR}/lib" "${NETCDF_DIR}/include" "${BASE_DIR}/env"

# --------------------------------------------------------------------
# Helper: extract installation root from `spack find -p`
# --------------------------------------------------------------------
get_spack_path() {
    local pkg="$1"
    # Get first absolute path only
    local path
    path=$(spack find -p "$pkg" | grep -Eo '/[^ ]+' | head -n 1 || true)
    if [[ -z "$path" ]]; then
        echo "❌  $pkg not found via spack" >&2
        return 1
    fi
    echo "Detected $pkg → $path" >&2    # goes to screen
    echo "$path"                        # clean path for variable
}

# --------------------------------------------------------------------
# Locate library roots
# --------------------------------------------------------------------
NETCDF_C_PATH=$(get_spack_path netcdf-c)
NETCDF_F_PATH=$(get_spack_path netcdf-fortran)
PNETCDF_PATH=$(get_spack_path parallel-netcdf)

if [[ -z "$NETCDF_C_PATH" || -z "$NETCDF_F_PATH" || -z "$PNETCDF_PATH" ]]; then
    echo "❌ Error: Could not locate one or more required packages via Spack."
    exit 1
fi

echo
echo "Detected library paths:"
echo "  NetCDF-C        → $NETCDF_C_PATH"
echo "  NetCDF-Fortran  → $NETCDF_F_PATH"
echo "  Parallel-NetCDF → $PNETCDF_PATH"
echo

# --------------------------------------------------------------------
# Symlink NetCDF contents
# --------------------------------------------------------------------
for dir in bin include lib; do
    echo "Linking $dir from NetCDF-C and NetCDF-Fortran..."
    for src in "$NETCDF_C_PATH/$dir" "$NETCDF_F_PATH/$dir"; do
        if [[ -d "$src" ]]; then
            ln -sf "$src/"* "${NETCDF_DIR}/$dir/" 2>/dev/null || true
        else
            echo "   [WARN] Directory not found: $src"
        fi
    done
done

# --------------------------------------------------------------------
# Write wrfgc.env
# --------------------------------------------------------------------
cat > "$ENV_FILE" <<EOF
# --------------------------------------------------------------------
# WRF-GC Environment Configuration
# Auto-generated by setup script on $(date)
# --------------------------------------------------------------------

spack env activate wrfgc
module load jasper

export CC=gcc
export OMPI_CC=\$CC
export CXX=g++
export OMPI_CXX=\$CXX
export FC=gfortran
export F77=\$FC
export F90=\$FC
export OMPI_FC=\$FC
export COMPILER=\$FC
export ESMF_COMPILER=gfortran

# MPI Communication
export ESMF_COMM=openmpi
export MPI_ROOT=\$MPI_HOME

export NETCDF=${NETCDF_DIR}
export NETCDF_HOME=\$NETCDF
export NETCDF_FORTRAN_HOME=\$NETCDF

export PNETCDF=${PNETCDF_PATH}

export JASPERLIB=\$JASPER_HOME/lib
export JASPERINC=\$JASPER_HOME/include

# WRF options
export WRF_EM_CORE=1
export WRF_NMM_CORE=0
export WRF_CHEM=1

# Needed for WRFv4
export NETCDF_classic=1

# GEOS-Chem extras
export OMP_STACKSIZE=1000000000
export KMP_STACKSIZE=\$OMP_STACKSIZE

# Base paths
export GC_BIN="\$NETCDF_HOME/bin"
export GC_INCLUDE="\$NETCDF_HOME/include"
export GC_LIB="\$NETCDF_HOME/lib"

# If using NetCDF after the C/Fortran split (4.3+)
export GC_F_BIN="\$NETCDF_FORTRAN_HOME/bin"
export GC_F_INCLUDE="\$NETCDF_FORTRAN_HOME/include"
export GC_F_LIB="\$NETCDF_FORTRAN_HOME/lib"
EOF

# --------------------------------------------------------------------
# Summary
# --------------------------------------------------------------------
echo
echo "✅ GEOS-Chem NetCDF environment setup complete!"
echo "  NetCDF contents linked under: $NETCDF_DIR"
echo "  Environment file created at:  $ENV_FILE"
echo
echo "To activate the environment, run:"
echo "  source $ENV_FILE"
